# RESTART SERVER TO ACTION CHANGES IN THIS FILE

# Site settings
title:        "Example Example CV"
description:  "CV of Example Example"
baseurl:      "/miikyla.github.io"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style:    compressed

# CV Contact Information
contact-name:       "Firstname Lastname"

resume-title:       "Software Engineer"

show-email:         true
contact-email:      "example@example.com"

show-phone:         true
contact-phone:      "(+61) 400 000 000"

show-location:      true
contact-location:   "Example, Australia"

contact-photo:      true
contact-photo-file: "assets/images/headshot.jpg"

executive-summary:      true
executive-summary-text: "Write executive summary here. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

show-references:    false

# CV sections
section-awards:             true
section-certificates:       true
section-contact:            true
section-education:          true
section-experience:         true
section-extra-curriculars:  true
section-languages:          true
section-projects:           true
section-skills:             true
section-references:         true

# Additional links
show-linkedin:          true
show-github:            true
show-resume-pdf:        true

linkedin-url:           "https://www.linkedin.com/in/.../"
github-url:             "https://github.com/..."
resume-pdf-file:        "assets/files/resume.pdf"