# RESTART SERVER TO ACTION CHANGES IN THIS FILE

# Site settings
title:        "Example Example CV"
description:  "CV of Example Example"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style:    compressed

# CV Contact Information
contact_name:       "Firstname LastName"

show_email:         true
contact_email:      "example@example.com"

show_phone:         true
contact_phone:      "(+61) 400 000 000"

show_location:      true
contact_location:   "Example, Australia"

contact_photo:      true
contact_photo_file: "_data/images/example.png"

executive_summary:      true
executive_summary_text: "<p>Write executive summary here.</p>"

# CV sections
section_awards:             true
section_certificates:       true
section_contact:            true
section_education:          true
section_experience:         true
section_extra_curriculars:  true
section_languages:          true
section_projects:           true
section_skills:             true

# Additional links
show_linkedin:          true
show_github:            true
show_stackoverflow:     true
show_resume_pdf:        true

linkedin_url:           "https://www.linkedin.com/in/.../"
github_url:             "https://github.com/..."
stackoverflow_url:      "https://stackoverflow.com/users/.../..."
resume_pdf_file:        "_data/files/resume.pdf"